### ISSUE TITLE
Stop Redownloading After A Confirmed Download

### ISSUE THREAD

**Issue by crjmichiels** [lilianmallardeau/playlist-sync#3]
Once the script has downloaded an audio track, I then move it to a different folder. Is there anyway to prevent this from downloading the file again other than leaving a copy of the original in the playlist folder location?

**Comment by Volcanios** [comment]
I don't think so

**Comment by Volcanios** [comment]
A possible solution, creating a json file where all the music you have already download is in. You check this json file before downloading any song. And add a command to clear this file.

**Comment by yayuniversal** [comment]
Hi @crjmichiels,
I'm sorry but this is not how `playlist-sync` is intended to work. It is designed to keep in sync your Deezer/Spotify playlists with the specified folders. So yeah, if a file is missing, it will be downloaded again.
